[package]
name = "rename-padded-numbers"
version = "0.1.0"
authors = ["Fuzen <me@fuzen.cafe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
